# Generated by Django 6.1.1 on 2026-09-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pet_type', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('rabbit', 'Rabbit')], max_length=20)),
                ('hunger', models.IntegerField(default=70)),
                ('happiness', models.IntegerField(default=70)),
                ('energy', models.IntegerField(default=70)),
                ('coins', models.IntegerField(default=100)),
            ],
        ),
    ]
