# Generated by Django 6.1.1 on 2026-09-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_last_updated_alter_pet_pet_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('hunger_boost', models.IntegerField(default=0)),
                ('happiness_boost', models.IntegerField(default=0)),
                ('energy_boost', models.IntegerField(default=0)),
            ],
        ),
    ]
